[mypy]
python_version = 3.9
exclude = (?x)(
    ^scripts/
    | ^tests/
    | ^doc/
    | ^setup\.py$
  )

# --strict
warn_unused_configs = True
# disallow_any_generics = True
disallow_subclassing_any = True
# disallow_untyped_calls = True
# disallow_untyped_defs = True
disallow_incomplete_defs = True
check_untyped_defs = True
disallow_untyped_decorators = True
# no_implicit_optional = True
warn_redundant_casts = True
warn_unused_ignores = True
# warn_return_any = True
# no_implicit_reexport = True
strict_equality = True

# Other strictness flags
warn_unreachable = True

# Output
show_error_codes = True
pretty = True

[mypy-colorama]
ignore_missing_imports = True

[mypy-hunter]
ignore_missing_imports = True

[mypy-pygments.*]
ignore_missing_imports = True

[mypy-cssutils]
ignore_missing_imports = True

[mypy-pypeg2]
ignore_missing_imports = True

[mypy-bdb]
ignore_missing_imports = True

[mypy-qutebrowser.browser.webkit.rfc6266]
disallow_subclassing_any = False

[mypy-qutebrowser.qt]
ignore_errors = True

[mypy-qutebrowser.app]
ignore_errors = True

[mypy-qutebrowser.api.cmdutils]
ignore_errors = True

[mypy-qutebrowser.api.config]
ignore_errors = True

[mypy-qutebrowser.api.hook]
ignore_errors = True

[mypy-qutebrowser.browser.browsertab]
ignore_errors = True

[mypy-qutebrowser.browser.commands]
ignore_errors = True

[mypy-qutebrowser.browser.downloads]
ignore_errors = True

[mypy-qutebrowser.browser.downloadview]
ignore_errors = True

[mypy-qutebrowser.browser.eventfilter]
ignore_errors = True

[mypy-qutebrowser.browser.greasemonkey]
ignore_errors = True

[mypy-qutebrowser.browser.hints]
ignore_errors = True

[mypy-qutebrowser.browser.inspector]
ignore_errors = True

[mypy-qutebrowser.browser.network.pac]
ignore_errors = True

[mypy-qutebrowser.browser.network.proxy]
ignore_errors = True

[mypy-qutebrowser.browser.pdfjs]
ignore_errors = True

[mypy-qutebrowser.browser.qtnetworkdownloads]
ignore_errors = True

[mypy-qutebrowser.browser.qutescheme]
ignore_errors = True

[mypy-qutebrowser.browser.urlmarks]
ignore_errors = True

[mypy-qutebrowser.browser.webelem]
ignore_errors = True

[mypy-qutebrowser.browser.webengine.certificateerror]
ignore_errors = True

[mypy-qutebrowser.browser.webengine.darkmode]
ignore_errors = True

[mypy-qutebrowser.browser.webengine.interceptor]
ignore_errors = True

[mypy-qutebrowser.browser.webengine.tabhistory]
ignore_errors = True

[mypy-qutebrowser.browser.webengine.webenginedownloads]
ignore_errors = True

[mypy-qutebrowser.browser.webengine.webengineelem]
ignore_errors = True

[mypy-qutebrowser.browser.webengine.webengineinspector]
ignore_errors = True

[mypy-qutebrowser.browser.webengine.webenginequtescheme]
ignore_errors = True

[mypy-qutebrowser.browser.webengine.webenginesettings]
ignore_errors = True

[mypy-qutebrowser.browser.webengine.webenginetab]
ignore_errors = True

[mypy-qutebrowser.browser.webengine.webview]
ignore_errors = True

[mypy-qutebrowser.browser.webkit.cookies]
ignore_errors = True

[mypy-qutebrowser.browser.webkit.mhtml]
ignore_errors = True

[mypy-qutebrowser.browser.webkit.network.networkmanager]
ignore_errors = True

[mypy-qutebrowser.browser.webkit.network.networkreply]
ignore_errors = True

[mypy-qutebrowser.browser.webkit.network.webkitqutescheme]
ignore_errors = True

[mypy-qutebrowser.browser.webkit.tabhistory]
ignore_errors = True

[mypy-qutebrowser.browser.webkit.webkitelem]
ignore_errors = True

[mypy-qutebrowser.browser.webkit.webkithistory]
ignore_errors = True

[mypy-qutebrowser.browser.webkit.webkitinspector]
ignore_errors = True

[mypy-qutebrowser.browser.webkit.webkitsettings]
ignore_errors = True

[mypy-qutebrowser.browser.webkit.webkittab]
ignore_errors = True

[mypy-qutebrowser.browser.webkit.webpage]
ignore_errors = True

[mypy-qutebrowser.browser.webkit.webview]
ignore_errors = True

[mypy-qutebrowser.commands.command]
ignore_errors = True

[mypy-qutebrowser.commands.userscripts]
ignore_errors = True

[mypy-qutebrowser.completion.completer]
ignore_errors = True

[mypy-qutebrowser.completion.completiondelegate]
ignore_errors = True

[mypy-qutebrowser.completion.completionwidget]
ignore_errors = True

[mypy-qutebrowser.completion.models.completionmodel]
ignore_errors = True

[mypy-qutebrowser.completion.models.histcategory]
ignore_errors = True

[mypy-qutebrowser.completion.models.listcategory]
ignore_errors = True

[mypy-qutebrowser.components.adblock]
ignore_errors = True

[mypy-qutebrowser.components.braveadblock]
ignore_errors = True

[mypy-qutebrowser.components.misccommands]
ignore_errors = True

[mypy-qutebrowser.components.readlinecommands]
ignore_errors = True

[mypy-qutebrowser.components.scrollcommands]
ignore_errors = True

[mypy-qutebrowser.components.zoomcommands]
ignore_errors = True

[mypy-qutebrowser.config.config]
ignore_errors = True

[mypy-qutebrowser.config.configcommands]
ignore_errors = True

[mypy-qutebrowser.config.configexc]
ignore_errors = True

[mypy-qutebrowser.config.configfiles]
ignore_errors = True

[mypy-qutebrowser.config.configtypes]
ignore_errors = True

[mypy-qutebrowser.config.configutils]
ignore_errors = True

[mypy-qutebrowser.config.stylesheet]
ignore_errors = True

[mypy-qutebrowser.config.websettings]
ignore_errors = True

[mypy-qutebrowser.extensions.loader]
ignore_errors = True

[mypy-qutebrowser.keyinput.basekeyparser]
ignore_errors = True

[mypy-qutebrowser.keyinput.eventfilter]
ignore_errors = True

[mypy-qutebrowser.keyinput.keyutils]
ignore_errors = True

[mypy-qutebrowser.keyinput.macros]
ignore_errors = True

[mypy-qutebrowser.keyinput.modeman]
ignore_errors = True

[mypy-qutebrowser.keyinput.modeparsers]
ignore_errors = True

[mypy-qutebrowser.mainwindow.mainwindow]
ignore_errors = True

[mypy-qutebrowser.mainwindow.messageview]
ignore_errors = True

[mypy-qutebrowser.mainwindow.prompt]
ignore_errors = True

[mypy-qutebrowser.mainwindow.statusbar.bar]
ignore_errors = True

[mypy-qutebrowser.mainwindow.statusbar.command]
ignore_errors = True

[mypy-qutebrowser.mainwindow.statusbar.percentage]
ignore_errors = True

[mypy-qutebrowser.mainwindow.statusbar.textbase]
ignore_errors = True

[mypy-qutebrowser.mainwindow.statusbar.url]
ignore_errors = True

[mypy-qutebrowser.mainwindow.tabbedbrowser]
ignore_errors = True

[mypy-qutebrowser.mainwindow.tabwidget]
ignore_errors = True

[mypy-qutebrowser.mainwindow.windowundo]
ignore_errors = True

[mypy-qutebrowser.misc.backendproblem]
ignore_errors = True

[mypy-qutebrowser.misc.checkpyver]
ignore_errors = True

[mypy-qutebrowser.misc.consolewidget]
ignore_errors = True

[mypy-qutebrowser.misc.crashdialog]
ignore_errors = True

[mypy-qutebrowser.misc.crashsignal]
ignore_errors = True

[mypy-qutebrowser.misc.earlyinit]
ignore_errors = True

[mypy-qutebrowser.misc.editor]
ignore_errors = True

[mypy-qutebrowser.misc.guiprocess]
ignore_errors = True

[mypy-qutebrowser.misc.httpclient]
ignore_errors = True

[mypy-qutebrowser.misc.ipc]
ignore_errors = True

[mypy-qutebrowser.misc.keyhintwidget]
ignore_errors = True

[mypy-qutebrowser.misc.miscwidgets]
ignore_errors = True

[mypy-qutebrowser.misc.msgbox]
ignore_errors = True

[mypy-qutebrowser.misc.quitter]
ignore_errors = True

[mypy-qutebrowser.misc.sessions]
ignore_errors = True

[mypy-qutebrowser.misc.throttle]
ignore_errors = True

[mypy-qutebrowser.misc.utilcmds]
ignore_errors = True

[mypy-qutebrowser.utils.debug]
ignore_errors = True

[mypy-qutebrowser.utils.jinja]
ignore_errors = True

[mypy-qutebrowser.utils.log]
ignore_errors = True

[mypy-qutebrowser.utils.message]
ignore_errors = True

[mypy-qutebrowser.utils.objreg]
ignore_errors = True

[mypy-qutebrowser.utils.qtutils]
ignore_errors = True

[mypy-qutebrowser.utils.standarddir]
ignore_errors = True

[mypy-qutebrowser.utils.urlutils]
ignore_errors = True

[mypy-qutebrowser.utils.usertypes]
ignore_errors = True

[mypy-qutebrowser.utils.utils]
ignore_errors = True

[mypy-qutebrowser.utils.version]
ignore_errors = True
